### ISSUE TITLE
Hacktoberfest-2020

### ISSUE THREAD

**Issue by Anishukla** [Anishukla/Hacktoberfest-2021-Data-Structures-and-Algorithms#1]
Hello folks, Want to contribute to Hacktoberfest. 
Confused about what to contribute? 
Let's make your task simpler. 
Go and check out the README of this repo and start contributing! 
Generate PRs for Hacktoberfest-2020 just by solving problems on Data Structures and Algorithms.
Happy Learning!!!

**Comment by arynn-gupta** [comment]
Added Depth FIrst Search . Please merge https://github.com/Anishukla/Algorithms/pull/2

**Comment by Anishukla** [comment]
@arynn-gupta Ig you have added an empty file.

**Comment by MSECoder** [comment]
I would like to contribute to this issue.

**Comment by Anishukla** [comment]
Yeah sure @MSECoder !!

**Comment by arynn-gupta** [comment]
Added Depth FIrst Search . Please merge https://github.com/Anishukla/Hacktoberfest-2020-Data-Structures-and-Algorithms/pull/9

**Comment by Anishukla** [comment]
@arynn-gupta merged! Thanks for contributing!

**Comment by sukhwal13** [comment]
added Trie Data Structure Please merge

**Comment by Anishukla** [comment]
@sukhwal13 Merged your contribution. Thanks!

**Comment by tuannm-1876** [comment]
@Anishukla I added a bubble sorting algorithm here.
https://github.com/Anishukla/Hacktoberfest-2020-Data-Structures-and-Algorithms/pull/20

**Comment by tuannm-1876** [comment]
@Anishukla I added a sorting algorithm here https://github.com/Anishukla/Hacktoberfest-2020-Data-Structures-and-Algorithms/pull/22

**Comment by Anishukla** [comment]
@tuannm-1876, please add the files in the "Searching and Sorting" folder inside the "Data Structures" folder.

**Comment by tuannm-1876** [comment]
> @tuannm-1876, please add the files in the "Searching and Sorting" folder inside the "Data Structures" folder.

Ok https://github.com/Anishukla/Hacktoberfest-2020-Data-Structures-and-Algorithms/pull/24

**Comment by Anishukla** [comment]
@tuannm-1876, merged your changes.
Thanks for contributing!

**Comment by vatsalya-gupta** [comment]
I want to contribute 3 to 4 algos

**Comment by Anishukla** [comment]
@vatsalya-gupta Sure, go ahead!

**Comment by vatsalya-gupta** [comment]
@Anishukla Added, please review the PRs

**Comment by hardiktaluja** [comment]
@Anishukla I have raised a PR for Linked List Creation and Traversal in Java.
Also added some ideas to extend this project a little bit more.
Do let me know your thoughts on that.

**Comment by Anishukla** [comment]
@vatsalya-gupta Will review your PRs and keep you posted!

**Comment by Anishukla** [comment]
@hardiktaluja I'll review your PR and read your ideas ASAP.

**Comment by chicken-biryani** [comment]
I have added anagram,  Palindrome, Reverse each word in a string, reversing a word, Counting the number of vowels and constants in a string.

**Comment by Anishukla** [comment]
@vatsalya-gupta Reviewed and merged all the aligning PRs. Thanks for sharing some important algorithms. Star the repo to keep yourself informed.

**Comment by Anishukla** [comment]
@hardiktaluja Reviewed and merged all the aligning PRs. Great Work!

**Comment by Anishukla** [comment]
@chicken-biryani, Thanks for your contribution! 
Star the repo to keep yourself informed.

**Comment by ShubhamNagure** [comment]
Hi @Anishukla,
I would like to contribute here,
Thanks

**Comment by Anishukla** [comment]
@ShubhamNagure Sure, go ahead.

**Comment by akshay399** [comment]
hey @Anishukla i Added Breadth FIrst Search please do check.

**Comment by vighneshdeepweb** [comment]
want to contribute on this issue @Anishukla

**Comment by vighneshdeepweb** [comment]
#47  Pls revie my PR....

**Comment by Anishukla** [comment]
@akshay399 I'll review your code.

**Comment by Anishukla** [comment]
@vighneshdeepweb and @akshay399 merged your PRs.
Thanks for contributing
Do star the repo if you find the information here useful!

**Comment by Kavinraja-G** [comment]
@Anishukla  I have contributed to some Recursion problems #49 
Happy to Contribute! :)

**Comment by Anishukla** [comment]
@Kavinraja-G merged your PRs.
Thanks for contributing
Do star the repo if you find the information here useful!

**Comment by Abirami-S21** [comment]
I would like to contribute in python. Shall I do it?

**Comment by Anishukla** [comment]
Sure @Abirami-S21, go ahead!

**Comment by amoghrajesh** [comment]
Hey @Anishukla! I have added a solution to "Longest Common subsequence" in python. Please review and merge

**Comment by Anishukla** [comment]
Reviewed and merged your PR @amoghrajesh.
Thanks for contributing.
Do star the repo if you find information here useful!

**Comment by vatsalya-gupta** [comment]
@Anishukla Please add the label **_hacktoberfest-accepted_** to the closed pull requests.

**Comment by amoghrajesh** [comment]
@Anishukla right. As @vatsalya-gupta says it is needed you add the "hactoberfest-accepted" label to all closed PRs.

**Comment by Anishukla** [comment]
PRs count if:
Submitted during the month of October AND (
  The PR is labeled as hacktoberfest-accepted by a maintainer OR
  Submitted in a repo with the hacktoberfest topic AND (
    The PR is merged OR
    The PR has been approved
  )
)

This is what I've read in the notice which means that it's not necessary to label hacktoberfest-accepted if I merge your PR, as the repo already has hactoberfest as a topic.
Hope I've answered your queries @vatsalya-gupta and @amoghrajesh.

**Comment by vatsalya-gupta** [comment]
Yeah, thanks @Anishukla

**Comment by amoghrajesh** [comment]
> PRs count if:
> Submitted during the month of October AND (
> The PR is labeled as hacktoberfest-accepted by a maintainer OR
> Submitted in a repo with the hacktoberfest topic AND (
> The PR is merged OR
> The PR has been approved
> )
> )
> 
> This is what I've read in the notice which means that it's not necessary to label hacktoberfest-accepted if I merge your PR, as the repo already has hactoberfest as a topic.
> Hope I've answered your queries @vatsalya-gupta and @amoghrajesh.

Thanks @Anishukla it clarifies it :)

**Comment by ShubhamNagure** [comment]
HI @Anishukla ,

Please review #104 . It will be fun if this PR merged.
Thanks for the opportunity. 

Shubham

**Comment by Anishukla** [comment]
Reviewed and merged your PR @ShubhamNagure.
Thanks for contributing!

**Comment by excess30** [comment]
@Anishukla  Added the code for Rotate Array in cpp
