### ISSUE TITLE
Postfix Expression Evaluation (Stacks)

### ISSUE THREAD

**Issue by sanskruti-shahu** [Anishukla/Hacktoberfest-2021-Data-Structures-and-Algorithms#153]
I want to add code for Postfix Expression Evaluation.
In this Input will be Postfix Expression on which particular operations will be performed using stacks and output will be the result of that expression.
Eg. Input => 4 6 + 2 / 5 * 7 +    Output => 32
Evaluation =>((((4+6)/2)*5)+7)

Please, assign this issue to me under Hacktoberfest'21.

**Comment by sanskruti-shahu** [comment]
@Anishukla Please assign me this issue

**Comment by Manas0916** [comment]
Hey @Anishukla  can you Please assign this me ? I want to solve this Problem in java!
Thank You!

**Comment by Anishukla** [comment]
Hey @sanskruti-shahu, @Manas0916 you both can go on with your issues. Lemme know once you are done PR. Try raising questions in the main issue instead.
Happy contributing!

**Comment by sanskruti-shahu** [comment]
@Anishukla I already did PR for Prefix Evaluation 
check this out https://github.com/Anishukla/Hacktoberfest-2021-Data-Structures-and-Algorithms/pull/256
