### ISSUE TITLE
Hacktoberfest-2021

### ISSUE THREAD

**Issue by Anishukla** [Anishukla/Hacktoberfest-2021-Data-Structures-and-Algorithms#154]
Hello folks, Want to contribute to Hacktoberfest.
Confused about what to contribute?
Let's make your task simpler.
Go and check out the README of this repo and start contributing!
Generate PRs for Hacktoberfest-2021 just by solving problems on Data Structures and Algorithms.
Happy Learning!!!

**Comment by shubhamnag14** [comment]
Can I contribute Sorting Algorithm in python..please assign me this issue

**Comment by Vibhugupta10616** [comment]
Hi, can I contribute in Leetcode (java) folder.

**Comment by Anishukla** [comment]
@shubhamnag14 Go for it

**Comment by Anishukla** [comment]
@Vibhugupta10616 Ya, no problem just follow the proper file structure.

**Comment by Vibhugupta10616** [comment]
Thank You I have already created a pull request kindly check.

**Comment by Vibhugupta10616** [comment]
@Anishukla Thank You I have already created a pull request kindly check.

**Comment by Anishukla** [comment]
@Vibhugupta10616 merged your contribution.

**Comment by Vibhugupta10616** [comment]
@Anishukla Thank You, will be contributing more too.

**Comment by sanskruti-shahu** [comment]
@Anishukla I had make an issue and also a PR. Please have a look

**Comment by Anishukla** [comment]
@sanskruti-shahu merged your PR.

**Comment by yashguptaji** [comment]
pls assign me

**Comment by shardul-b** [comment]
@Anishukla can i contribute for 10 Days of JS (HackerRank)?

**Comment by RSMIT01** [comment]
@Anishukla i have made pull request by adding  N-queen  problem from leetcode in leetcode (c++) , pls check it.

**Comment by sanskruti-shahu** [comment]
Thank you!! @Anishukla

**Comment by mukeshmjn** [comment]
@RahulBansal0502 pr #216 issue #217 please merge it i have added solution!

**Comment by Vibhugupta10616** [comment]
@Anishukla kindly label the pr's as "hacktoberfest-accepted" otherwise they will not be recognized by hacktoberfest ream and will not reflect on our profiles.

**Comment by mukeshmjn** [comment]
@Vibhugupta10616 he is not even merging it

**Comment by Vibhugupta10616** [comment]
He is, but it is taking time for him as there are many.
Yesterday he merged 2 of my pr's.

**Comment by jcos201** [comment]
Hello, I'd like to add a frequency counter algorithm in JavaScript.

**Comment by Anishukla** [comment]
@mukeshmjn approved your PR.
@Vibhugupta10616 will be looking at it.
@jcos201 go ahead!
@shardul-b Yes, you can.
@RSMIT01 will do it.

**Comment by Vibhugupta10616** [comment]
> He is, but it is taking time for him as there are many. Yesterday he merged 2 of my pr's. But 1 of my pr's is also left, let's have some patience 👍

All of my prs are merged. Thanks @Anishukla

**Comment by Anishukla** [comment]
> He is, but it is taking time for him as there are many. Yesterday he merged 2 of my pr's. But 1 of my pr's is also left, let's have some patience +1

Everyone who's making a valid PR shouldn't worry, I've already merged 238 PRs. So, just have patience.

**Comment by HastiSutaria** [comment]
@Anishukla I want to contribute for HackerRank/Python. Can I add solutions of more than one problem?

**Comment by Anishukla** [comment]
@HastiSutaria Yup, you can.

**Comment by mukeshmjn** [comment]
@Anishukla when u will review so that it gets considered for hacktoberfest?

**Comment by shubhamnag14** [comment]
I have created one pull request please check it and do the needful

**Comment by Khushi-Shukla** [comment]
Please review and merge this PR #281

**Comment by Khushi-Shukla** [comment]
Created PR #314 which is the solution of a leetcode problem. Kindly review and merge it. Thank You.

**Comment by sanskruti-shahu** [comment]
@Anishukla Please review PR #319 and #215 and merge it.

**Comment by aditirao7** [comment]
@Anishukla Has the project been excluded?
