### ISSUE TITLE
[LeetCode] 189. Rotate Array

### ISSUE THREAD

**Issue by MrDoomy** [Anishukla/Hacktoberfest-2021-Data-Structures-and-Algorithms#190]
Hi 👋
I want to contribute on this repository by solving [189. Rotate Array](https://leetcode.com/problems/rotate-array
)
@Anishukla Can you assign this (under `hacktoberfest-2021` label) to me? 🤔

**Comment by Anishukla** [comment]
Done
Happy contributing!
