### ISSUE TITLE
 Implement Queue using Stacks

### ISSUE THREAD

**Issue by Ratna04priya** [Anishukla/Hacktoberfest-2021-Data-Structures-and-Algorithms#212]
Implementing Queue using Stacks in Java
 PR : #214 
 @RahulBansal0502 I have raised a PR for this issue.

**Comment by mukeshmjn** [comment]
Hi @RahulBansal0502 I would like to work in this

**Comment by mukeshmjn** [comment]
Can u add hacktoberfest tag as well

**Comment by Ratna04priya** [comment]
> Hi @RahulBansal0502 I would like to work in this

Hi @mukeshmjn, I have raised PR for this issue

**Comment by mukeshmjn** [comment]
@Ratna04priya in which branch u merged it?

**Comment by mukeshmjn** [comment]
@Ratna04priya are these issues being counted in hacktoberfest?

**Comment by RahulBansal0502** [comment]
Sorry guys @Ratna04priya @mukeshmjn I think you have some confusion I am not the maintainer of this repo. Happy Coding!
