### ISSUE TITLE
LeetCode Problem: 153.Find Minimum in Rotated Sorted Array in Java

### ISSUE THREAD

**Issue by Ratna04priya** [Anishukla/Hacktoberfest-2021-Data-Structures-and-Algorithms#253]
LeetCode Problem: 153.Find Minimum in Rotated Sorted Array in Java
Problem Link - https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/
PR: #254

**Comment by Anishukla** [comment]
Approved
Happy contributing!
