### ISSUE TITLE
Array and simple queries (hackerrank question)

### ISSUE THREAD

**Issue by pavitrapati** [Anishukla/Hacktoberfest-2021-Data-Structures-and-Algorithms#268]
I would like sincerely work on this issue. Please assign me this issue.

**Comment by pavitrapati** [comment]
I would like sincerely work on this issue. Please assign me this  issue.

**Comment by Anishukla** [comment]
Ya, go ahead.
Pick some algorithms that are not already present.
Happy contributing!
