### ISSUE TITLE
LeetCode: 718. Maximum Length of Repeated Subarray in Java 

### ISSUE THREAD

**Issue by Ratna04priya** [Anishukla/Hacktoberfest-2021-Data-Structures-and-Algorithms#298]
Problem : Leetcode - https://leetcode.com/problems/maximum-length-of-repeated-subarray/
718. Maximum Length of Repeated Subarray
Language- Java

PR: #300 

Example 1:
Input: nums1 = [1,2,3,2,1], nums2 = [3,2,1,4,7]
Output: 3
Explanation: The repeated subarray with maximum length is [3,2,1].

**Comment by Anishukla** [comment]
Approved
